############# English navigation ##############

# main menu
[[main]]
name = "Books"
url = "/book"
weight = 1

    [[main]]
    parent = "Books"
    name = "Get Your Hands Dirty on Clean Architecture"
    url = "/book"
    weight = 2

    [[main]]
    parent = "Books"
    name = "Stratospheric"
    url = "https://stratospheric.dev?utm_source=reflectoring&utm_content=sidebar"
    weight = 3

[[main]]
name = "Simplify"
url = "/simplify"
weight = 2

[[main]]
name = "Contribute"
weight = 3

    [[main]]
    parent = "Contribute"
    name = "Become an Author"
    url = "/contribute/become-an-author"
    weight = 1

    [[main]]
    parent = "Contribute"
    name = "Writing Guide"
    url = "/contribute/writing-guide"
    weight = 2

    [[main]]
    parent = "Contribute"
    name = "Author Workflow"
    url = "/contribute/author-workflow"
    weight = 3

    [[main]]
    parent = "Contribute"
    name = "Author Payment"
    url = "/contribute/author-payment"
    weight = 4

[[main]]
name = "Services"
weight = 4

    [[main]]
    parent = "Services"
    name = "Book me"
    url = "/book-me"
    weight = 4

    [[main]]
    parent = "Services"
    name = "Advertise"
    url = "advertise"
    weight = 5

[[main]]
name = "Categories"
weight = 6
hasChildren = true

      [[main]]
      parent = "Categories"
      name = "Spring Boot"
      url = "/categories/spring-boot/"
      weight = 1

      [[main]]
      parent = "Categories"
      name = "Java"
      url = "/categories/java/"
      weight = 2

      [[main]]
      parent = "Categories"
      name = "NodeJS"
      url = "/categories/node/"
      weight = 3

      [[main]]
      parent = "Categories"
      name = "AWS"
      url = "/categories/aws/"
      weight = 4

      [[main]]
      parent = "Categories"
      name = "Software Craft"
      url = "/categories/software-craft/"
      weight = 5

      [[main]]
      parent = "Categories"
      name = "Simplify!"
      url = "/categories/simplify/"
      weight = 6

      [[main]]
      parent = "Categories"
      name = "Meta"
      url = "/categories/meta/"
      weight = 7

# footer menu
[[footer]]
name = "Content"
weight = 1

    [[footer]]
    parent = "Content"
    name = "Spring Boot"
    url = "/categories/spring-boot/"
    weight = 1

    [[footer]]
    parent = "Content"
    name = "Java"
    url = "/categories/java/"
    weight = 2

    [[footer]]
    parent = "Content"
    name = "AWS"
    url = "/categories/aws/"
    weight = 2

    [[footer]]
    parent = "Content"
    name = "Software Craft"
    url = "/categories/software-craft/"
    weight = 3

    [[footer]]
    parent = "Content"
    name = "Simplify!"
    url = "/categories/simplify/"
    weight = 5

    [[footer]]
    parent = "Content"
    name = "Meta"
    url = "/categories/meta/"
    weight = 6

[[footer]]
name = "Products"
weight = 2

    [[footer]]
    parent = "Products"
    name = "Get Your Hands Dirty on Clean Architecture"
    url = "/book"
    weight = 1

    [[footer]]
    parent = "Products"
    name = "Simplify! Newsletter"
    url = "/simplify"
    weight = 2

    [[footer]]
    parent = "Products"
    name = "Stratospheric"
    url = "https://stratospheric.dev?utm_source=reflectoring&utm_content=sidebar"
    weight = 3

[[footer]]
name = "Contribute"
weight = 3

    [[footer]]
    parent = "Contribute"
    name = "Become an Author"
    url = "/contribute/become-an-author"
    weight = 1

    [[footer]]
    parent = "Contribute"
    name = "Writing Guide"
    url = "/contribute/writing-guide"
    weight = 2

    [[footer]]
    parent = "Contribute"
    name = "Author Workflow"
    url = "/contribute/author-workflow"
    weight = 3

    [[footer]]
    parent = "Contribute"
    name = "Author Payment"
    url = "/contribute/author-payment"
    weight = 4

[[footer]]
name = "Reflectoring"
weight = 4

    [[footer]]
    parent = "Reflectoring"
    name = "About"
    url = "/about"
    weight = 1

    [[footer]]
    parent = "Reflectoring"
    name = "Atom Feed"
    url = "/feed.xml"
    weight = 2

    [[footer]]
    parent = "Reflectoring"
    name = "Advertise"
    url = "/advertise"
    weight = 3

    [[footer]]
    parent = "Reflectoring"
    name = "Book me"
    url = "/book-me"
    weight = 4

    [[footer]]
    parent = "Reflectoring"
    name = "Privacy"
    url = "/privacy"
    weight = 5
